version: "3.7"
services:

  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: deployment/envoy.Dockerfile
    volumes:
      - ./deployment/envoy.yaml:/etc/envoy.yaml
    networks:
      envoymesh:
        ipv4_address: 172.28.1.1
        aliases:
          - envoy
    expose:
      - "1999"
      - "8081"
      - "8000"
    ports:
      - "1999:1999"
      - "8081:8081"
      - "8000:8000"

  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: deployment/mysql.Dockerfile
    networks:
      envoymesh:
        ipv4_address: 172.28.1.2
        aliases:
          - mysql
    environment:
        MYSQL_ROOT_PASSWORD: efishery-DataBase-01
    expose:
      - "3306"
    ports:
      - "3306:3306"

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: deployment/auth.Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      envoymesh:
        ipv4_address: 172.28.1.3
        aliases:
          - auth
    expose:
      - "7000"
    ports:
      - "7000:7000"

  fetch:
    container_name: fetch
    build:
      context: .
      dockerfile: deployment/fetching.Dockerfile
    networks:
      envoymesh:
        ipv4_address: 172.28.1.4
        aliases:
          - fetch
    expose:
      - "6000"
    ports:
      - "6000:6000"

  swagger:
    container_name: swagger
    build:
      context: .
      dockerfile: deployment/swagger.Dockerfile
    networks:
      envoymesh:
        ipv4_address: 172.28.1.5
        aliases:
          - swagger
    expose:
      - "9000"
    ports:
      - "9000:9000"

networks:
  envoymesh:
    name: envoymesh
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16