[config]
    [config.LOCALHOST]
    cors_url = ["*"]
    api_route_url = ":7000"
    redis_url = "localhost:6379"
    redis_pass = ""
    jwt_secret = "Efishery-JWT-Secret-Dev-010203"
    mode = "test"


    [config.PRODUCTION]
    cors_url = ["*"]
    api_route_url = ":7000"
    redis_url = "localhost:6450"
    redis_pass = "Efishery-Redis-Auth-2020"
    jwt_secret = "Efishery-JWT-Secret-010203"
    mode = "prod"
