[config]
    [config.LOCALHOST]
    cors_url = ["*"]
    api_route_url = ":7000"
    mysql_host = "127.0.0.1"
    mysql_port = "3306"
    mysql_user = "root"
    mysql_pass = "efishery-DataBase-01"
    jwt_secret = "Efishery-JWT-Secret-Dev-010203"
    mode = "test"


    [config.PRODUCTION]
    cors_url = ["*"]
    api_route_url = ":7000"
    mysql_host = "172.28.1.2"
    mysql_port = "3306"
    mysql_user = "root"
    mysql_pass = "efishery-DataBase-01"
    jwt_secret = "Efishery-JWT-Secret-010203"
    mode = "prod"
