[LOCALHOST]
cors_url = ["*"]
api_route_url = ":7000"
mysql_host = "localhost"
mysql_port = "3306"
mysql_user = "efishery-user"
mysql_pass = "efishery-DataBase-01"
jwt_secret = "Efishery-JWT-Secret-Dev-010203"
mode = "test"

[PRODUCTION]
cors_url = ["*"]
api_route_url = ":7000"
mysql_host = "localhost"
mysql_port = "3306"
mysql_user = "efishery-user"
mysql_pass = "efishery-DataBase-01"
jwt_secret = "Efishery-JWT-Secret-010203"
mode = "prod"
