[LOCALHOST]
cors_url = ["*"]
api_route_host = "0.0.0.0"
api_route_port = 6000
jwt_secret = "Efishery-JWT-Secret-Dev-010203"
mode = "test"

[PRODUCTION]
cors_url = ["*"]
api_route_host = "0.0.0.0"
api_route_port = 6000
jwt_secret = "Efishery-JWT-Secret-010203"
mode = "prod"
